version: '3'
services:
  pg:
      image: postgres:16-alpine
      environment:
        POSTGRES_DB: order_system
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_USER}
      volumes:
      - order_system:/var/lib/postgresql/data
      ports:
      - "5433:5432"
      healthcheck:
        test: [ "CMD-SHELL", "-U", "${POSTGRES_USER}", "pg_isready" ]
        interval: 5s
        timeout: 3s
        retries: 3

volumes:
  order_system: